job_index:
    path:     /
    defaults: { _controller: "EnsSimonBundle:Job:index" }
    methods:  GET

job_show:
    path:     /{company}/{location}/{id}/{position}
    defaults: { _controller: "EnsSimonBundle:Job:show" }
    requirements:
        id:  \d+
    methods:  GET

job_new:
    path:     /new
    defaults: { _controller: "EnsSimonBundle:Job:new" }
    methods:  [GET, POST]

job_edit:
    path:     /{id}/edit
    defaults: { _controller: "EnsSimonBundle:Job:edit" }
    methods:  [GET, POST]

job_delete:
    path:     /{id}/delete
    defaults: { _controller: "EnsSimonBundle:Job:delete" }
    methods:  DELETE
