job_index:
    path:     /
    defaults: { _controller: "EnsSimonBundle:Job:index" }
    methods:  GET

job_show:
    path:     /{company}/{location}/{id}/{position}
    defaults: { _controller: "EnsSimonBundle:Job:show" }
    requirements:
        id:  \d+
    methods:  GET

job_new:
    path:     /new
    defaults: { _controller: "EnsSimonBundle:Job:new" }
    methods:  [GET, POST]

job_edit:
    path:     /{token}/edit
    defaults: { _controller: "EnsSimonBundle:Job:edit" }
    methods:  [GET, POST]

job_delete:
    path:     /{token}/delete
    defaults: { _controller: "EnsSimonBundle:Job:delete" }
    methods:  DELETE

job_update:
    path:     /{token}/update
    defaults: { _controller: "EnsSimonBundle:Job:update" }
    methods:  DELETE

job_preview:
    path:  /{company}/{location}/{token}/{position}
    defaults: { _controller: "EnsSimonBundle:Job:preview" }
    requirements:
        token:  \w+